# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('pub_date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('occupation', models.CharField(max_length=60, null=True)),
                ('org_name', models.CharField(max_length=60, null=True)),
                ('phone_num', models.CharField(max_length=30, null=True)),
                ('profile_photo', models.ImageField(upload_to='profile/')),
                ('bio', models.TextField(max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
